SELECT PROJECT.PROJ_NAME, PROJECT.PROJ_VALUE, PROJECT.PROJ_BALANCE, EMPLOYEE.EMP_LNAME, EMPLOYEE.EMP_FNAME, EMPLOYEE.EMP_INITIAL, JOB.JOB_CODE, JOB.JOB_DESCRIPTION, JOB.JOB_CHG_HOUR
FROM ((PROJECT
INNER JOIN EMPLOYEE ON PROJECT.EMP_NUM=EMPLOYEE.EMP_NUM)
INNER JOIN JOB ON EMPLOYEE.JOB_CODE=JOB.JOB_CODE)
ORDER BY PROJ_VALUE;
